BulletinBoard/Board/urls.py
from django.urls import path
from . import views
from .views import AdsList, Ad, AdCreate, AdEdit, AdDelete, create_response

urlpatterns = [
    path('', AdsList.as_view(template_name='ads.html')),
    path('ads/', AdsList.as_view(), name='Ads'),
    path('ad/<int:pk>', Ad.as_view(), name='ad_detail'),
    path('ad/create/', AdCreate.as_view(), name='ad_create'),
    path('ad/<int:pk>/edit/', AdEdit.as_view(), name='ad_edit'),
    path('ad/<int:pk>/delete/', AdDelete.as_view(), name='ad_delete'),
    path('ad/<int:pk>/response/', views.create_response, name='create_response'),
    path('my-responses/', views.manage_responses, name='manage_responses'),
    path('accept-response/<int:response_id>/', views.accept_response, name='accept_response'),
    path('delete-response/<int:response_id>/', views.delete_response, name='delete_response'),
]

BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Board import views

urlpatterns = [
    path('admin/newsletter/', views.admin_newsletter, name='admin_newsletter'),
    path('admin/', admin.site.urls),
    path('', include('Board.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BulletinBoard/Board/models.py
from django.db import models
from django.contrib.auth.models import User


# модель для объявлений.
class Advertisement(models.Model):
    title = models.CharField(max_length=64)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    TANKS = 'TN'
    HEALERS = 'HL'
    DAMAGEDEALERS = 'DD'
    MERCHANTS = 'MC'
    GUILDMASTERS = 'GM'
    QUESTGIVERS = 'QG'
    BLACKSMITHS = 'BS'
    LEATHERWORKERS = 'LW'
    POTIONMASTERS = 'PM'
    SPELLMASTERS = 'SM'
    CATEGORY_CHOISES = (
        (TANKS, 'Танки'),
        (HEALERS, 'Хилы'),
        (DAMAGEDEALERS, 'ДД'),
        (MERCHANTS, 'Торговцы'),
        (GUILDMASTERS, 'Гилдмастеры'),
        (QUESTGIVERS, 'Квестгиверы'),
        (BLACKSMITHS, 'Кузнецы'),
        (LEATHERWORKERS, 'Кожевники'),
        (POTIONMASTERS, 'Зельевары'),
        (SPELLMASTERS, 'Мастера заклинаний')
    )
    category = models.CharField(max_length=2, choices=CATEGORY_CHOISES)
    dateCreation = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    upload = models.FileField(upload_to='uploads/', blank=True, null=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return f'/ad/{self.id}'


# модель для откликов
class Response(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
    text = models.TextField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"Отклик от пользователя {self.author} на объявление {self.advertisement.title}"

BulletinBoard/Board/forms.py
from django import forms
from .models import Advertisement, Response


# Форма для объявления
class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = [
            'title',
            'category',
            'text',
            'image',
            'upload'
        ]


# Форма для отклика
class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ['text']


# Форма для новостной рассылки
class NewsletterForm(forms.Form):
    subject = forms.CharField(max_length=200, label="Тема")
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")

BulletinBoard/Board/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import send_mail, send_mass_mail
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import AdvertisementForm, ResponseForm, NewsletterForm
from .models import Advertisement, Response


# представление страницы с объявлениями
class AdsList(ListView):
    model = Advertisement
    template_name = 'ads.html'
    context_object_name = 'Ads'
    paginate_by = 10
    ordering = ['-dateCreation']


# представление страницы объявления
class Ad(DetailView):
    template_name = 'ad.html'
    context_object_name = 'ad'
    queryset = Advertisement.objects.all()


# представление страницы создания объявления
class AdCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('board.add_advertisement',)
    form_class = AdvertisementForm
    model = Advertisement
    template_name = 'ad_edit.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# представление страницы редактирования объявления
class AdEdit(PermissionRequiredMixin, UpdateView):
    permission_required = ('board.change_advertisement',)
    form_class = AdvertisementForm
    model = Advertisement
    template_name = 'ad_edit.html'


# представление страницы удаления объявления
class AdDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('board.delete_advertisement',)
    model = Advertisement
    template_name = 'ad_delete.html'
    success_url = reverse_lazy('Ads')


# представление страницы отклика
def create_response(request, pk):
    ad = get_object_or_404(Advertisement, id=pk)
    if request.method == 'POST':
        form = ResponseForm(request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            response.advertisement = ad
            response.author = request.user
            response.save()

            # отправка уведомления автору объявления
            send_mail(
                'Новый отклик на ваше объявление',
                f'{request.user} ответил на ваше объявление "{ad.title}".',
                'no-reply@yourwebsite.com',
                [ad.author.email],
                fail_silently=False,
            )

            return redirect('ad_detail', pk=pk)
    else:
        form = ResponseForm()
    return render(request, 'response_form.html', {'form': form, 'ad': ad})


# представление страницы с просмотром всех откликов
def manage_responses(request):
    if not request.user.is_authenticated:
        return redirect('login')

    status_filter = request.GET.get('status')
    responses = Response.objects.filter(advertisement__author=request.user)

    if status_filter == "accepted":
        responses = responses.filter(status=True)
    elif status_filter == "pending":
        responses = responses.filter(status=False)

    ads_with_responses = Advertisement.objects.filter(id__in=responses.values_list('advertisement_id', flat=True))

    return render(request, 'manage_responses.html', {'ads_with_responses': ads_with_responses})


# представление принятия отклика
def accept_response(request, response_id):
    response = get_object_or_404(Response, id=response_id)
    if response.advertisement.author != request.user:
        return HttpResponseForbidden()

    response.status = True
    response.save()

    send_mail(
        'Ваш отклик был принят!',
        'Ваш отклик на объявление "{}" был принят. Спасибо за интерес!'.format(response.advertisement.title),
        'danila04092002@yandex.ru',
        [response.author.email],
        fail_silently=False,
    )

    return redirect('manage_responses')


# представление отклонения отклика
def delete_response(request, response_id):
    response = get_object_or_404(Response, id=response_id)
    if response.advertisement.author != request.user:
        return HttpResponseForbidden()

    response.delete()
    return redirect('manage_responses')


# представление отправки новостей
def send_newsletter(email_subject, email_message):
    users = User.objects.all()
    recipient_list = [user.email for user in users if user.email]
    send_mail(
        email_subject,
        email_message,
        'danila04092002@yandex.ru',
        recipient_list,
        fail_silently=False,
    )


# представление страницы с отправкой новостей
def admin_newsletter(request):
    if request.method == "POST":
        form = NewsletterForm(request.POST)
        if form.is_valid():
            send_newsletter(form.cleaned_data['subject'], form.cleaned_data['message'])
            messages.success(request, "Рассылка отправлена!")
            return redirect('admin_newsletter')
    else:
        form = NewsletterForm()
    return render(request, 'admin_newsletter_template.html', {'form': form})

BulletinBoard/templates/ad.html
{% extends 'flatpages/default.html' %}

{% block title %}
Объявления
{% endblock title %}

{% block content %}
    <h1>{{ ad.title }}</h1>
    <p>{{ ad.dateCreation|date:'d M Y' }}</p>
    <p>{{ ad.text }}</p>
    <p>Автор объявления: {{ ad.author }}</p>
    <br>
    {% if object.image %}
        <img width='500' src="{{ object.image.url }}">
    {% endif %}
    <br>
    {% if object.upload %}
       <a href="{{ ad.upload.url }}" download>Скачать файл</a>
    {% endif %}
    {% if user.is_authenticated and user != ad.author %}
        <a href="{% url 'create_response' pk=ad.id %}">Оставить отклик</a>
    {% endif %}
    {% if user.is_authenticated and user == ad.author %}
        <a href="{% url 'ad_edit' pk=ad.id %}">Редактировать</a>
        <a href="{% url 'ad_delete' pk=ad.id %}">Удалить</a>
    {% endif %}
{% endblock content %}

BulletinBoard/templates/ad_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удалить объявление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p> Вы хотите удалить {{ post.title }}?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

BulletinBoard/templates/ad_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать объявление</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

BulletinBoard/templates/admin_newsletter_template.html
{% extends 'flatpages/default.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить рассылку</button>
</form>
{% endblock %}

BulletinBoard/templates/ads.html
{% extends 'flatpages/default.html' %}

{% block title %}
Объявления
{% endblock title %}

{% block content %}

<hr>
    {% if user.is_authenticated %}
        <a href="{% url 'ad_create' %}">Добавить объявление</a>
    {% endif %}
<hr>
        <table>
            <tr>
                <td>Название</td>
                <td>Дата публикации</td>
                <td>Текст</td>
            </tr>

            {% for ad in Ads %}
            <tr>
                <td><a href="{% url 'ad_detail' ad.id %}">{{ ad.title }}</a></td>
                <td>{{ ad.dateCreation|date:'d M Y' }}</td>
                <td>{{ ad.text|truncatewords:20 }}</td>
                <td>
                    {% if user.is_authenticated and user == ad.author %}
                        <a href="{% url 'ad_edit' pk=ad.id %}">Редактировать</a>
                        <a href="{% url 'ad_delete' pk=ad.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
           {% if page_obj.has_previous %}
               <a href="?page=1">1</a>
               {% if page_obj.previous_page_number != 1 %}
                   ...
                   <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
               {% endif %}
           {% endif %}

           {{ page_obj.number }}

           {% if page_obj.has_next %}
               <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
               {% if paginator.num_pages != page_obj.next_page_number %}
                   ...
                   <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
               {% endif %}
           {% endif %}
{% endblock content %}

BulletinBoard/templates/index.html
{% extends 'flatpages/default.html' %}

{% load socialaccount %}

{% block title %}
Index page
{% endblock title %}

{% block content %}
{% if user.is_authentificated %}
<h1>Здравствуйте</h1>
<p>Вы зашли, как {{ user.username }}</p>
{% else %}
<a href="{% provider_login_url 'yandex' %}">Войдите с Yandex</a>
{% endif %}
{% endblock content %}

BulletinBoard/templates/manage_responses.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Управление откликами</h2>

<form method="get">
    <select name="status">
        <option value="">Все отклики</option>
        <option value="accepted" {% if status_filter == "accepted" %}selected{% endif %}>Принятые</option>
        <option value="pending" {% if status_filter == "pending" %}selected{% endif %}>Ожидающие</option>
    </select>
    <input type="submit" value="Фильтровать">
</form>

{% for ad in ads_with_responses %}
    <h3>{{ ad.title }}</h3>
    {% for response in ad.response_set.all %}
        <div class="response">
            <p>{{ response.text }}</p>
            <a href="{% url 'accept_response' response.pk %}">Принять</a>
            <a href="{% url 'delete_response' response.pk %}">Удалить</a>
        </div>
    {% endfor %}
{% endfor %}
{% endblock %}

BulletinBoard/templates/response_form.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Ответить на объявление: "{{ ad.title }}"</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
{% endblock %}